### ISSUE TITLE
[BUG] No explaination on how to run PHP files for Lab 9 using mySQL on Docker

### ISSUE THREAD

**Issue by jeffreyv101** [PostGuitarist/liberty-macos-docs#10]
**Describe the bug**
There is no page that describes how to run PHP files on the mySQL database that is created with Docker

**Expected behavior**
Explaination given for this lab.

**Additional context**
How to execute PHP files for Lab 9.

**Comment by PostGuitarist** [comment]
Can you describe what you mean by running PHP files on the mySQL db? I don't know what the assignment details are for that.

**Comment by jeffreyv101** [comment]
Here are the assignment instructions, this lab has always been in CSCN 326, so if you have taken the class you should be able to go back and look at it:
CSCN 326 – Lab 9 Instructions
PHP Programming
Why Learn This?
• Develop basic web programming skills and ensure access to a properly installed web
server
Prerequisite
• Perform or Review PHP Setup Workshop Instructions, located in the PHP Lab folder in
Blackboard.
• Read/Review How LAMP Is Used Today
Learning Objectives
• Understand the various technologies needed to accomplish web programming
Resources
• LAMP/WAMP installed computer
• 60 minutes
Tasks
1. Perform or Review the PHP Setup Workshop
2. Execute http://localhost/PHP-Example.php from the step above
3. Note one valid SID from the records displayed in the step above
4. Access the course folder
5. Copy PHP-Example.php and rename it PHP-Changed.php
6. Change the SQL statement in PHP-Changed.php to include a WHERE clause that selects
only the one SID noted above --- see comments in the PHP file
7. Save the changed script and execute http://localhost/PHP-Changed.php
8. Verify only that single record is retrieved
9. Submit a zip file containing a screen shot of your output (saved in a Word document) and
your PHP-Changed.php file to the appropriate assignment link in Canvas.

**Comment by PostGuitarist** [comment]
https://github.com/PostGuitarist/liberty-macos-docs/pull/11

This has been merged. Take a look at the end of the MySQL section.
